-- MySQL Script generated by MySQL Workbench
-- sáb 30 out 2021 00:16:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venda_material
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda_material
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda_material` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `venda_material` ;

-- -----------------------------------------------------
-- Table `venda_material`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `carrinho_produto_idx` (`produto_id` ASC),
  CONSTRAINT `carrinho_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `venda_material`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `carrinho_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_compra_idx` (`usuario_id` ASC),
  INDEX `compra_carrinho_idx` (`carrinho_id` ASC),
  CONSTRAINT `usuario_compra`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `venda_material`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_carrinho`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `venda_material`.`carrinho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
