-- MySQL Script generated by MySQL Workbench
-- sáb 20 nov 2021 22:18:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venda_material
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda_material
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda_material` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `venda_material` ;

-- -----------------------------------------------------
-- Table `venda_material`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL DEFAULT 1,
  `vendedor_id` INT NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_carrinho_vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_carrinho_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `venda_material`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrinho_id` INT NOT NULL,
  `modo_pagamento` VARCHAR(45) NOT NULL,
  `total` DOUBLE NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_venda_carrinho_idx` (`carrinho_id` ASC),
  CONSTRAINT `fk_venda_carrinho`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `venda_material`.`carrinho` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_material`.`produto_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_material`.`produto_carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrinho_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_carrinho_idx` (`produto_id` ASC),
  INDEX `fk_carrinho_produto_idx` (`carrinho_id` ASC),
  CONSTRAINT `fk_produto_carrinho`
    FOREIGN KEY (`produto_id`)
    REFERENCES `venda_material`.`produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrinho_produto`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `venda_material`.`carrinho` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
